spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  redis:
    host: localhoost
    port: 8888
    password: 00
connector:
  routes:
    1: zhajinhua
    2: paodekuai
    3: baijiale
    4: douniu
