spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  redis:
    host: localhoost
    port: 8888
    password: 00
hall:
  routes:
    1: hallserver
    2: yingsanzhang
    3: paodekuai
    4: baijiale
    5: douniu
  name: hallserver
netty-websocket:
  host: 127.0.0.1
  port: 80
  path: /