spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  redis:
    host: localhoost
    port: 8888
    password: 00
game:
  servers:
    - ip: localhost
      port: 8080
      name: 服务器1
    - ip: localhost
      port: 8080
      name: 服务器2
jwt:
  secret: ASDF1234a
  expiration: 120000